name: tavern
version: 1.3.4
description: An open-source pub.dev client for searching and subscribing to packages
environment: 
  sdk: '>=2.6.0 <3.0.0'

dependencies: 
  provider: ^3.1.0+1
  flutter_bloc: ^2.0.0
  dynamic_overflow_menu_bar: ^0.1.2
  package_info: ^0.4.0+10
  dynamic_theme: ^1.0.1
  get_it: ^3.0.3
  hive: ^1.1.1
  url_launcher: ^5.2.5
  cupertino_icons: ^0.1.2
  groovin_material_icons: ^1.1.6
  rounded_modal: ^1.0.1
  html2md: ^0.5.0
  material_segmented_control: ^2.0.4
  groovin_widgets: ^1.4.2
  bloc: ^2.0.0
  flutter_pagewise: any
  hydrated_bloc: ^2.0.0
  webfeed: ^0.4.2
  background_fetch: ^0.3.2
  flutter_local_notifications: ^0.8.4
  flutter_markdown: ^0.3.0
  flutter_svg: ^0.14.4
  share: ^0.6.3+1

  flutter: 
    sdk: flutter
  pub_client:
    git: https://github.com/ThinkDigitalSoftware/pub_client.git

dev_dependencies: 
  build_runner: ^1.7.2
  hanzo: ^1.0.2
  pedantic: ^1.8.0+1
  pubspec: ^0.1.2
  github: ^6.0.0
  args: ^1.5.2

flutter:
  assets: 
    - images/
  fonts: 
    - 
      family: Metropolis
      fonts: 
        - 
          asset: fonts/Metropolis-Regular.otf
  uses-material-design: true
authors: 
  - Jonathan White <jwhite@thinkdigital.software>
  - GroovinChip <groovinchip@gmail.com>
