name: tavern
version: 1.5.5
description: An open-source pub.dev client for searching and subscribing to packages
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  provider: ^4.1.3
  flutter_bloc: ^4.0.1
  dynamic_overflow_menu_bar: ^0.1.2
  package_info: ^0.4.1
  dynamic_theme: ^1.0.1
  get_it: ^4.0.2
  hive: ^1.4.1+1
  url_launcher: ^5.4.11
  cupertino_icons: ^0.1.3
  groovin_material_icons: ^1.1.6
  rounded_modal: ^1.0.1
  html2md: ^0.5.1
  material_segmented_control: ^2.1.0+1
  groovin_widgets: ^1.5.0+4
  bloc: ^4.0.0
  flutter_pagewise: any
  hydrated_bloc: ^4.1.1
  webfeed: ^0.4.2
  background_fetch: ^0.6.0
  flutter_local_notifications: ^1.4.4+1
  flutter_markdown: ^0.4.2
  flutter_svg: ^0.17.4
  share: ^0.6.4+3
  syntax_highlighter:
    git: https://github.com/ThinkDigitalSoftware/syntax_highlighter.git
  flutter_secure_storage: ^3.3.1+1
  github: ^6.1.2
  flutter_progress_button: ^1.0.0
  google_fonts: ^0.3.8
  auto_size_text: ^2.1.0
  flutter_launcher_icons: ^0.7.4
  autotrie: ^0.1.2

  flutter:
    sdk: flutter
  pub_client:
    git: https://github.com/ThinkDigitalSoftware/pub_client.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  hanzo: ^1.0.2
  pubspec: ^0.1.4
  args: ^1.5.2
  effective_dart: ^1.2.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/web_hi_res_512.png"

flutter:
  assets:
    - assets/
  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Regular.otf
  uses-material-design: true

authors:
  - Jonathan White <jwhite@thinkdigital.software>
  - GroovinChip <groovinchip@gmail.com>
