name: tavern
version: 1.2.2
description: An open-source pub.dev client for searching and subscribing to packages

environment: 
  sdk: '>=2.2.2 <3.0.0'

dependencies: 
  provider: ^3.1.0
  flutter_bloc: ^0.21.0
  dynamic_overflow_menu_bar: ^0.1.1
  package_info: ^0.4.0+6
  dynamic_theme: ^1.0.1
  get_it: ^3.0.0+1
  hive: ^1.0.0
  url_launcher: ^5.1.3
  cupertino_icons: ^0.1.2
  groovin_material_icons: ^1.1.6
  rounded_modal: ^1.0.1
  back_button_interceptor: ^4.1.1
  html2md: ^0.3.2
  material_segmented_control: ^2.0.3
  syntax_highlighter: ^0.1.0
  groovin_widgets: ^1.4.2
  bloc: ^0.15.0
  path_provider: ^1.3.0
  shared_preferences: ^0.5.3+4
  flutter_pagewise: any
  hydrated_bloc: ^0.4.1
  webfeed: ^0.4.2
  flutter_markdown: 
    git: https://github.com/ThinkDigitalSoftware/flutter_markdown.git
  flutter: 
    sdk: flutter
  pub_client: 
    git: https://github.com/ThinkDigitalSoftware/pub_client.git

dev_dependencies:
  build_runner: ^1.7.0
  hive_generator: 0.5.1
  hanzo: ^1.0.2
  pedantic: ^1.8.0+1
  pubspec: ^0.1.2

flutter: 
  assets: 
    - images/
  fonts: 
    - 
      family: Metropolis
      fonts: 
        - 
          asset: fonts/Metropolis-Regular.otf
  uses-material-design: true

authors: 
  - Jonathan White <jwhite@thinkdigital.software>
  - GroovinChip <groovinchip@gmail.com>
